### ISSUE TITLE
How to conduct the Crime Data (NYC, CHI) experiment

### ISSUE THREAD

**Issue by xueyagaga** [HKUDS/STExplainer#3]
Now we can only reproduce the experiment of PEMS4 data set, how to analyze the crime data? 
If convenient, could you tell me how to obtain the raw data (NYC, CHI) and conduct the experiment using your method.
In addition, whether your project must run in Ubuntu environment. It is difficult to configure dependency packages in Windows 10.

**Comment by tjb-tech** [comment]
> Now we can only reproduce the experiment of PEMS4 data set, how to analyze the crime data? If convenient, could you tell me how to obtain the raw data (NYC, CHI) and conduct the experiment using your method. In addition, whether your project must run in Ubuntu environment. It is difficult to configure dependency packages in Windows 10.

Thank you for your interests on our work. 
1. We will release the implements of our method on Crime Data soon (by the end of Friday) including the data. 
2. We only run our project in Ubuntu environment, so I am not sure about running in Windows 10. You could show your error information and let's figure out it! 
Hope my answer is help for you. Wishing you an early Merry Christmas!
